name: Build and Deploy
on:
  push:
    branches:
      - feature
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install and Build
        run: |
          npm ci --ignore-scripts
          npm run build

      - name: Add .nojekyll file
        run: |
          touch dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist
          branch: gh-pages
          clean: true
          single-commit: true
